### ISSUE TITLE
database yml config missing host?

### ISSUE THREAD

**Issue by cctrbic** [sparc-request/sparc-request#892]
What is the complete database configuration ?
Example included in database.yml.example
  username: root
  adapter: mysql2
  encoding: utf8
  database: sparc_rails_development
  pool: 5
  timeout: 5000
Are we missing "host" ? 
I'm trying to set a remote database, but not sure where this information is set. Thanks

**Comment by jayhardee9** [comment]
Yes, you should have something like:
```
production:
  adapter: mysql2
  database: sparc_production
  host: some_db_server_hostname
  username: some_user
  password: some_password
```
